coverage:
  precision: 1
  round: down
  range: 70...100

  status:
    project: true
    threshold: 1%
    changes: false

    patch:
      default:
        target: 70%

comment:
  layout: "header, diff"
  behavior: default

ignore:
  - "dallinger/heroku/rq_gevent_worker"
