coverage:
  precision: 1
  round: up
  range: 70...100

  status:
    project:
      default:
        threshold: 1%

    patch:
      default:
        target: 70%

    changes: false

comment:
  layout: "header, diff"
  behavior: default

ignore:
  - "dallinger/heroku/rq_gevent_worker"
