coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project: true
    threshold: 0.1
    patch: false
    changes: false

comment:
  layout: "header, diff"
  behavior: default

ignore:
  - "dallinger/heroku/rq_gevent_worker"
