coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project: true
    threshold: 0.1
    changes: false

    patch:
      default:
        target: 50%

comment:
  layout: "header, diff"
  behavior: default

ignore:
  - "dallinger/heroku/rq_gevent_worker"
