repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.4
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      files: ^(tests|dallinger|dallinger_scripts|demos)/
      types_or: [python, pyi]
    - id: ruff-format
      files: ^(tests|dallinger|dallinger_scripts|demos)/
      types_or: [python, pyi]
