label_prs: "dependencies"
search: False
requirements:
  - constraints.txt:
      update: all
      pin: True
  - requirements.txt:
      update: False
      pin: False
  - dev-requirements.txt:
      update: False
      pin: False
