version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
    nodejs: "latest"
  jobs:
    post_install:
      - npm install -g jsdoc

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

sphinx:
  configuration: docs/source/conf.py
