version: '3.7'
services:
  postgresql:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dallinger
      POSTGRES_PASSWORD: dallinger
      POSTGRES_DB: dallinger
    volumes:
      - dallinger_pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  dallinger_pg_data: