web: /home/cguardia/work/jazkarta/dallinger/bin/python launch.py
worker: /home/cguardia/work/jazkarta/dallinger/bin/python worker.py
clock: /home/cguardia/work/jazkarta/dallinger/bin/python clock.py

