name: continuous-integration
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: CI
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: postgres:12
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: dallinger
          POSTGRES_PASSWORD: dallinger
          POSTGRES_DB: dallinger
    steps:
      - name: Check out Dallinger repository
        uses: actions/checkout@v2
      - name: Install Ubuntu packages
        run: sudo apt-get --yes install pandoc enchant snapd curl
      - name: Install snap packages
        run: sudo snap install --classic heroku
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Install node packages
        run: npm add -g yarn && yarn --frozen-lockfile --ignore-engines
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Ruby dependencies
        run: |
          gem install danger
          gem install danger-commit_lint
          gem install chandler -v 0.7.0
      - name: Yarn
        run: yarn --frozen-lockfile --ignore-engines
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('build-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Python Installers
        run: |
          pip install --upgrade pip wheel tox
      - name: Before Tox
        run: |
          bundle exec danger
      - name: Run Full Tox
        env:
          DATABASE_URL: postgresql://dallinger:dallinger@localhost/dallinger
          PORT: 5000
          base_port: 5000
          threads: 1
          mturk_worker_id: ${{ secrets.MTURK_WORKER_ID }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          tox
        if: matrix.python-version == 3.9
      - name: Run Fast Tests Only
        env:
          DATABASE_URL: postgresql://dallinger:dallinger@localhost/dallinger
          PORT: 5000
          base_port: 5000
          threads: 1
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          tox -e fast
        if: matrix.python-version != 3.9
      - name: Set up deployment
        env:
          CHANDLER_GITHUB_API_TOKEN: ${{ secrets.CHANDLER_GITHUB_API_TOKEN }}
        run: |
          pandoc --from=markdown --to=rst --output=README.rst README.md
          pip install build
          python -m build --sdist --wheel .
          chandler push --tag-prefix=v
        if: matrix.python-version == 3.9 && contains(github.ref, '/tags/v')
      - name: Deploy
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
        if: matrix.python-version == 3.9 && contains(github.ref, '/tags/v')

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: pip install black
    - uses: pre-commit/action@v2.0.0
    
