name: Release
on:
  push:
    branches:
      - optimize-dallinger-docker-image

jobs:
  docker-images:
    runs-on: ubuntu-latest
    environment: ghcr
    steps:
      - name: Get version
        id: vars
        run: echo "version=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT
      - name: Login to Github ghcr
        uses: docker/login-action@v3
        with:
          # The GHCR_TOKEN in Dallinger's ghcr environment was created by user silviot
          username: silviot
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build ghcr.io/dallinger/dallinger docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          load: false
          target: dallinger
          tags: |
            ghcr.io/dallinger/dallinger:latest-slim
      - name: Build ghcr.io/dallinger/dallinger-bot docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          load: false
          target: dallinger-bot
          tags: |
            ghcr.io/dallinger/dallinger-bot:latest-slim
