name: Release
on:
  push:
    tags:
      - v*
    branches:
      - upgrade-to-python3.13

jobs:
  release:
    runs-on: ubuntu-latest
    environment: pypi
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Install Ubuntu packages
        run: sudo apt-get --yes install curl enchant-2 pandoc
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install node packages
        run: yarn --frozen-lockfile --ignore-engines
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Python Installers
        run: pip install --upgrade pip wheel tox
      - name: Set up deployment
        run: |
          pandoc --from=markdown --to=rst --output=README.rst README.md
          pip install build
          python -m build --sdist --wheel .
      - name: Deploy
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  docker-images:
    runs-on: ubuntu-latest
    environment: ghcr
    steps:
      - name: Get version
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "version=python3.13" >> $GITHUB_OUTPUT
          fi
      - name: Login to Github ghcr
        uses: docker/login-action@v3
        with:
          # The GHCR_TOKEN in Dallinger's ghcr environment was created by user silviot
          username: silviot
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build ghcr.io/dallinger/dallinger docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          load: false
          target: dallinger
          tags: |
            ghcr.io/dallinger/dallinger:python3.13
      - name: Build ghcr.io/dallinger/dallinger-bot docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          load: false
          target: dallinger-bot
          tags: |
            ghcr.io/dallinger/dallinger-bot:python3.13
